### ISSUE TITLE
After Carrying Capacity is added to backend, add it to the AdminListCommons page

### ISSUE THREAD

**Issue by YYA0** [ucsb-cs156-f22/f22-6pm-happycows#55]
Add CarryingCapacity to CommonsTable.js and AdminListCommonPage.js so that the Carrying Capacity can be seen on those pages.

**Comment by sergioacolis** [comment]
https://github.com/ucsb-cs156-f22/f22-6pm-happycows/pull/57

**Comment by YYA0** [comment]
LGTM 
working well on Heroku.
